# Generated by Django 4.1.2 on 2023-04-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_book_edition_alter_book_publication_year'),
    ]

    operations = [
    ]
