# Generated by Django 4.1.2 on 2023-04-27 14:15

from django.db import migrations
from devpro.core.models import Author, Book
from faker import Faker

fake = Faker()


def populate_database(apps, schema_editor):
    for _ in range(25):
        author = Author.objects.create(name=fake.name())
        book = Book.objects.create(name=fake.text(),
                                   edition=fake.random_int(),
                                   publication_year=fake.year(),
                                   )
        book.authors.set([author])
        book.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_book_edition_alter_book_publication_year'),
    ]

    operations = [
        migrations.RunPython(populate_database)
    ]
